craigslist-jr/config/routes.rb
Rails.application.routes.draw do

  # root to: "categories#index"
  root "categories#index"

  resources :categories, only: [:index, :show] do
    resources :articles, except: [:edit, :update, :destroy]
  end

  get "/categories/:category_id/articles/:id/edit/:auth_key" => "articles#edit",
  as: "edit_article"

  patch "/categories/:category_id/articles/:id" => "articles#update",
  as: "update_article"

  delete "/categories/:category_id/articles/:id" => "articles#destroy",
  as: "article_delete"

  # get "/categories" => "categories#index"
  # get "/categories/:id" => "categories#show"
  # get "/articles" => "articles#index",
  # as: "article_index"
  # get "/articles/new" => "articles#new"
  # get "/articles/:id" => "articles#show",
  # as: "article_show"
  # post "/articles" => "articles#create"
end

craigslist-jr/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
end

craigslist-jr/app/models/authorization_key.rb
module AuthorizationKey

  SET_TO_SAMPLE_FROM = ('0'..'9').to_a + ('a'..'z').to_a

  def self.auth_key
    SET_TO_SAMPLE_FROM.sample(5).join
  end

end

craigslist-jr/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

craigslist-jr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

craigslist-jr/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params.merge(auth_key: AuthorizationKey.auth_key))

    if @article.save
      redirect_to edit_article_path(@article.category, @article.id, @article.auth_key)
    else
      render :action => "new"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article= Article.find(params[:id])

    @article.assign_attributes(article_params)

    if @article.save
      redirect_to category_article_path(@article.category,@article)
    else
      render :action => "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:success] = "Article deleted"

    redirect_to category_articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, :category_id)
  end

end

craigslist-jr/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

end

craigslist-jr/app/helpers/application_helper.rb
module ApplicationHelper
end

craigslist-jr/app/views/articles/edit.html.erb
<h2 style="color:red;"><b>Please bookmark this page so that you can edit and delete your article</b></h2>

<%= form_for @article, url: {action: 'update'}, html: {class:"article_form"} do |f| %>
  <%=f.label :title%>
  <%=f.text_field  :title%>
  <%=f.label :description%>
  <%=f.text_area :description, size: "50x10"%>
  <%=f.collection_select :category_id, Category.order(:name),:id,:name%>
  <%=f.submit "Edit"%>
<%end %>

<p><%= link_to 'DELETE THIS ARTICLE', category_article_path, :method => :delete %></p>

craigslist-jr/app/views/articles/index.html.erb
<h1>All Articles</h1>

<% @articles.each do |article| %>
  <p><%= link_to "#{article.title}", category_article_path(article.category,article) %></p>
<% end %>
<br>
<br>
<%= link_to 'ADD A NEW ARTICLE', new_category_article_path %>

craigslist-jr/app/views/articles/new.html.erb
<%= form_for @article, url: {action: 'create'}, html: {class:"article_form"} do |f| %>
  <%=f.label :title %>
  <%=f.text_field  :title%>
  <%=f.label :description %>
  <%=f.text_area :description, size: "50x10" %>
  <%=f.collection_select :category_id, Category.order(:name),:id,:name %>
  <%=f.submit "Create" %>
<%end %>

craigslist-jr/app/views/articles/show.html.erb
<h2><%=@article.title%></h2>

<p><%=@article.description%> </p>

craigslist-jr/app/views/categories/index.html.erb
<h1>All Categories</h1>

<% @categories.each do |category| %>
  <p><%= link_to "#{category.name}", category_path(category)  %></p>
<% end %>

craigslist-jr/app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% @category.articles.each do |article| %>
  <h3><%= link_to "#{article.title}", category_article_path(@category,article) %></h3>
<% end %>

<p><%= link_to 'CREATE NEW ARTICLE', new_category_article_path(@category) %></p>

craigslist-jr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraigslistJr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>

<div><%= link_to "HOME", categories_path %></div>

</nav>
<%= yield %>

</body>
</html>